version: '3.7'

services:
    rimutec-piranha:
        container_name: rimutec-piranha-dev
        build:
            context: .
        working_dir: /app
        volumes:
            - ..:/app:cached
        depends_on:
            - database
        command: >
            bash -c "pwsh /app/dev/init.ps1 && pwsh /app/dev/setversion.ps1 && sleep infinity"

    database:
        container_name: rimutec-piranha-dev-db
        image: mcr.microsoft.com/mssql/server
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=PassWord42
        ports:
            - 7605:1433
